sonar.projectKey=devops-project-19-java
sonar.projectName=DevOps Project 19 - Java Sample
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
